fix: OTP Input inputs delay bug
BlazorComponent/BlazorComponent pull request #100
Opened 2022-04-11 10:51 UTC by gavin1ee

fix: OTP Input inputs delay bug

2022-04-24 08:48 UTC, capdiem requested changes

2022-04-24 08:48 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/interop.ts
> +                return {
emmm js使用两个空格作为tab。

2022-04-25 02:31 UTC, capdiem approved these changes

2022-04-25 03:34 UTC, doddgu approved these changes
LGTM

2022-04-25 03:34 UTC, merged