feature(form):fluentValidation-DependencyInjection
BlazorComponent/BlazorComponent pull request #149
Opened 2022-06-13 09:56 UTC by 15168440402

2022-06-13 10:07 UTC, doddgu commented
@capdiem PTAL

2022-06-14 01:32 UTC, capdiem requested changes

2022-06-14 01:32 UTC, capdiem commented on src/Component/BlazorComponent/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
> +            services.AddFluentValidation();
可以使用官方的DI吗？https://docs.fluentvalidation.net/en/latest/di.html

2022-06-14 03:00 UTC, capdiem approved these changes
LGTM. @doddgu

2022-06-14 03:05 UTC, doddgu approved these changes
LGTM

2022-06-14 03:05 UTC, merged