refactor(Input): Change the logic of TextField input and rendering
BlazorComponent/BlazorComponent pull request #199
Opened 2022-09-07 08:19 UTC by capdiem

2022-09-07 10:10 UTC, doddgu requested changes

2022-09-07 10:10 UTC, doddgu commented on src/Component/BlazorComponent/Components/Form/EditContext/ValidationEventSubscriptions.cs
> +
Remove this blank line.

2022-09-07 10:10 UTC, doddgu commented on src/Component/BlazorComponent/Components/TextField/TextFieldAbstractProviderExtensions.cs
> +            // XXX: 有缺陷，无法覆盖和合并Input对应元素
xxx?

2022-09-07 10:10 UTC, doddgu commented on src/Component/BlazorComponent/Components/TextField/TextFieldAbstractProviderExtensions.cs
> +            // XXX: 有缺陷，无法覆盖和合并Input对应元素
另外这个缺陷会导致什么问题，举个例子？

2022-09-07 15:22 UTC, capdiem commented on src/Component/BlazorComponent/Components/TextField/TextFieldAbstractProviderExtensions.cs
> +            // XXX: 有缺陷，无法覆盖和合并Input对应元素
添加了一个Merge重载

2022-09-08 01:20 UTC, doddgu approved these changes
LGTM

2022-09-08 01:20 UTC, merged