Add Nullable detection and eliminate warnings
BlazorComponent/BlazorComponent pull request #261
Opened 2022-12-13 02:08 UTC by tzm1119

添加可控检查

2022-12-13 02:37 UTC, capdiem commented on src/Component/BlazorComponent/Abstracts/ComponentKey.cs
> +            Name = "";
从28行判断这个Name是可以为null的吧，应该把24行`string`改成`string?`？

2022-12-13 02:37 UTC, capdiem commented on src/Component/BlazorComponent/Abstracts/ComponentCssProvider.cs
> +        public ComponentCssProvider Merge(Action<CssBuilder>? mergeCssAction = null, Action<StyleBuilder>? mergeStyleAction = null)
63行的两个action也需要加`?`的吧

2022-12-13 02:37 UTC, capdiem requested changes

2022-12-13 02:37 UTC, capdiem commented on src/Component/BlazorComponent/BlazorComponent.csproj
> +		<Nullable>enable</Nullable>
缩进不对。

2022-12-21 05:36 UTC, capdiem requested changes

2022-12-21 05:36 UTC, capdiem commented on src/Component/BlazorComponent/Services/OneOf/StringBoolean.cs
> +        return Convert.ToString(Value)??"";
因为`Convert.ToString(null) => "null"`，所以我觉得应该把ToString()的返回类型改为`string?`

2022-12-21 05:36 UTC, capdiem commented on src/Component/BlazorComponent/Services/OneOf/StringEnum.cs
> +        return Value?.ToString() ?? "null";
不应该返回字符串null，把ToString()的返回类型改为string?吧

2022-12-21 05:36 UTC, capdiem commented on src/Component/BlazorComponent/Services/OneOf/StringNumber.cs
> +        return Value?.ToString() ?? "null";
不应该返回字符串null，把ToString()的返回类型改为string?吧

2022-12-21 05:36 UTC, capdiem commented on src/Component/BlazorComponent/Services/OneOf/StringNumberBoolean.cs
> +        return Convert.ToString(Value) ?? "";
不应该返回字符串null，把ToString()的返回类型改为string?吧

2022-12-21 06:02 UTC, capdiem approved these changes
LGTM @doddgu

2022-12-21 09:30 UTC, doddgu approved these changes
LGTM

2022-12-21 09:31 UTC, merged