feat: Add baidumap js code and update build script
BlazorComponent/BlazorComponent pull request #298
Opened 2023-01-21 12:24 UTC by msnoshain

# Description

Add baidumap js code and update build script to support [MBaiduMap](https://github.com/BlazorComponent/MASA.Blazor/pull/951) component.

To update baidumap js code, edit:
`/src/proxies/maps/baidumap/index.js`

To rebuild js, run: 
`.\build-js.ps1 maps`

2023-01-22 15:51 UTC, capdiem requested changes

2023-01-22 15:51 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +    window.BMapGL_loadScriptTime = (new Date).getTime();
`BMAP_PROTOCOL`和`BMapGL_loadScriptTime` 有什么作用？我没找到相应的文档

2023-01-22 15:51 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +var map;
据我所知，多个组件会共享这一个`map`，会被覆盖，建议你在 `loadMap` 里直接 return `map`。

2023-01-22 15:51 UTC, capdiem commented on src/Component/BlazorComponent.Web/rollup.config.maps.ts
> +  plugins: [typescript(), terser()],
没有使用 ts，不用 `typescript()`

2023-01-22 15:51 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +async function injectBaiduMapScript(ak) {
动态添加脚本，如果我有五个map组件，那不得下载五次？

2023-01-22 15:51 UTC, capdiem commented on src/Component/BlazorComponent.Web/build-js.ps1
> +  [ValidateSet("main", "echarts", "input", "markdownit", "gridstack", "activatable", "outsideclick", "maps")]
```suggestion
  [ValidateSet("main", "echarts", "input", "markdownit", "gridstack", "activatable", "outsideclick", "baidumap")]
```

2023-01-22 18:12 UTC, msnoshain commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +var map;
我试了试，在浏览器控制台里是访问不到map的。是不是意味着这里已经被隔离了？只有在组件内部才能访问到

2023-01-22 18:13 UTC, msnoshain commented on src/Component/BlazorComponent.Web/build-js.ps1
> +  [ValidateSet("main", "echarts", "input", "markdownit", "gridstack", "activatable", "outsideclick", "maps")]
这里需要改好几个地方。稍后我手动改完再提交

2023-01-22 18:21 UTC, msnoshain commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +    window.BMapGL_loadScriptTime = (new Date).getTime();
按照百度的官方文档，为了使用地图，需要将一个script放入head中，在页面加载时会执行该script进行一些初始化。但经过测试，利用blazor组件的形式加载时，该script并不会被执行。于是我手动访问了该script指向的src，将其中需要执行的语句复制进该函数。

2023-01-22 18:22 UTC, msnoshain commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +    window.BMapGL_loadScriptTime = (new Date).getTime();
> `BMAP_PROTOCOL`和`BMapGL_loadScriptTime` 有什么作用？我没找到相应的文档

这两个变量在百度官方的js代码中有用到

2023-01-22 18:30 UTC, msnoshain commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +async function injectBaiduMapScript(ak) {
> 动态添加脚本，如果我有五个map组件，那不得下载五次？

我会在这里添加判断是否已经注入过脚本的代码

2023-01-23 02:13 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +var map;
两个map组件用的是同一个`map`变量，会被覆盖

2023-01-23 02:29 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +    window.BMapGL_loadScriptTime = (new Date).getTime();
相比直接静态脚本，动态写入 script 复杂度提升了许多 😂

2023-01-23 06:15 UTC, msnoshain commented
代码修改已完成😊 @capdiem

2023-01-24 15:23 UTC, capdiem requested changes

2023-01-24 15:23 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +        return await loadMap(containerID);
少了`initArgs`，ID改为Id

2023-01-24 15:29 UTC, capdiem requested changes

2023-01-24 15:29 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +        map.centerAndZoom(new BMapGL.Point(initArgs.mapCenter.x, initArgs.mapCenter.y), initArgs.zoom);
`canZoom`和`mapCenter`不是官方的api名称欸，我觉得改为官方的那种比较合适。可参考[React的](https://huiyan.baidu.com/github/react-bmapgl/#/%E5%9F%BA%E7%A1%80%E7%B1%BB/Map)。

2023-01-24 15:31 UTC, msnoshain commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +        map.centerAndZoom(new BMapGL.Point(initArgs.mapCenter.x, initArgs.mapCenter.y), initArgs.zoom);
收到，我再改改

2023-01-26 06:50 UTC, capdiem requested changes

2023-01-26 06:50 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +var dotNetObjectReference;
为什么外面定义这个？用不上，况且会被覆盖。

2023-01-26 06:50 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +    try {
不用`try catch`了，不是动态下载script。

2023-01-26 06:50 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +async function initMap(containerId, initArgs, dotNetObjRef) {
```suggestion
async function init(containerId, initArgs, dotNetObjRef) {
```

2023-01-26 06:50 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +            map.disableScrollWheelZoom();
不用else部分，如果map实例默认不能scrollWheelZoom。

2023-01-27 03:35 UTC, capdiem requested changes

2023-01-27 03:35 UTC, capdiem commented on src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
> +    map.centerAndZoom(new BMapGL.Point(initArgs.center.x, initArgs.center.y), initArgs.zoom);
```suggestion
    map.centerAndZoom(initArgs.center, initArgs.zoom);
```
最这样最好了。

2023-01-27 10:02 UTC, capdiem approved these changes
LGTM @doddgu

2023-01-29 07:02 UTC, doddgu approved these changes
LGTM，thanks for pr

2023-01-29 07:02 UTC, merged