feat: Support for dynamic theme modification
BlazorComponent/BlazorComponent pull request #299
Opened 2023-01-22 06:57 UTC by LittleFish-233

# Description
Associate the PR
https://github.com/BlazorComponent/MASA.Blazor/pull/952

2023-01-22 16:08 UTC, capdiem requested changes

2023-01-22 16:08 UTC, capdiem commented on src/Component/BlazorComponent/Components/App/BApp.razor
> +            <div class="@CssProvider.GetClass()" style="@CssProvider.GetStyle()" id="@Id" @ref="Ref" @attributes="Attributes">
整页缩进都不对。

2023-01-22 16:08 UTC, capdiem commented on src/Component/BlazorComponent/Components/App/BApp.razor.cs
> +        protected string Styles { get; set; } = "";
命名为 ThemeStyleMarkups 更贴切一点吧

2023-02-03 03:50 UTC, doddgu approved these changes
LGTM

2023-02-03 04:11 UTC, merged