Feature/0.4.0/otpinput
BlazorComponent/BlazorComponent pull request #80
Opened 2022-03-25 07:19 UTC by gavin1ee

add OTP input Component

2022-03-25 07:34 UTC, doddgu commented
@capdiem

2022-03-26 10:00 UTC, capdiem requested changes

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/BOtpInput.razor.cs
> +        public StringNumber Length { get; set; } = "6";
使用数字6。

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/BOtpInput.razor.cs
> +        public bool Light { get; set; } = true;
Light缺少[Parameter]，并且缺少CascadingIsDark。

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/BOtpInput.razor.cs
> +        public List<ElementReference> Elements { get; set; } = new();
建议命名InputRefs

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/BOtpInput.razor.cs
> +            for (int i = 0; i < Length.ToInt32(); i++)
放在初始化里，有个问题：Length是一个入参，如果用户修改了，例如从6到5，组件会动态渲染吗？

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/slot/BOtpInputSlot.razor.cs
> +        [Parameter]
Parameter放在最上面，CascadingParameter之后

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/slot/BOtpInputSlot.razor.cs
> +                await OnKeyup.InvokeAsync(new BOtpInputKeyboardEventArgs() { Args = args, Index = index });
BOtpInputKeyboardEventArgs建议写个构造函数重载

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Web/PasteWithDataEventArgs.cs
> +        public string PastedData{ get; set; }
格式，所有代码检查下格式。

2022-03-26 10:00 UTC, capdiem commented on src/Component/BlazorComponent/Components/OtpInput/BOtpInput.razor
> +
空行太多了。

2022-03-28 03:44 UTC, closed without merging