Feature/0.4.0/textfield support number
BlazorComponent/BlazorComponent pull request #88
Opened 2022-03-30 03:56 UTC by gavin1ee

feat(component): TextField component supper number type

2022-04-02 05:47 UTC, capdiem requested changes

2022-04-02 05:47 UTC, capdiem commented on src/Component/BlazorComponent/Components/TextField/Content/Control/InputSlot/DefaultSlot/NumberIconSlot/BTextFieldNumberIconSlot.razor
> +    var upButtonchildContent = RenderPart(typeof(BInputIcon<,>), "append-icon-number-up", "mdi-chevron-up", HandleOnNumberUpClickAsync, arg0Name: "Type", arg1Name: "Icon", arg2Name: "OnClick");
child -> Child

2022-04-02 05:47 UTC, capdiem commented on src/Component/BlazorComponent/Components/TextField/Content/Control/InputSlot/DefaultSlot/NumberIconSlot/BTextFieldNumberIconSlot.razor
> +        @RenderPart(typeof(BInputSlot<,>),"append","inner",downButtonChildContent,arg0Name:"Type","Location","ChildContent")
add a whitespace after comma.

2022-04-02 05:47 UTC, capdiem commented on src/Component/BlazorComponent/Components/TextField/TextFieldNumberProperty.cs
> +        public bool ShowControl { get; set; } = true;
改成HideControl如何？ @doddgu

2022-04-06 06:33 UTC, capdiem approved these changes
LGTM. @doddgu

2022-04-06 11:35 UTC, doddgu approved these changes
LGTM

2022-04-06 11:35 UTC, merged