feat: float action button
BlazorComponent/BlazorComponent pull request #97
Opened 2022-04-09 02:32 UTC by gavin1ee

feat: float action button

2022-04-24 08:06 UTC, capdiem requested changes

2022-04-24 08:06 UTC, capdiem commented on src/Component/BlazorComponent/Components/SpeedDial/BSpeedDial.razor
> +    @if (Transition != null)
不用判断Transition是否为空了。

2022-04-24 08:06 UTC, capdiem commented on src/Component/BlazorComponent/Components/SpeedDial/BSpeedDial.razor.cs
> +        private string Tag { get; set; } = "div";
`private`放在`protected`前面。

2022-04-25 02:34 UTC, capdiem approved these changes

2022-04-25 02:34 UTC, doddgu approved these changes
LGTM

2022-04-25 02:34 UTC, merged